import type {
  PreviewAIExplanation,
  PreviewAICoachingResponse,
  PreviewBookmarkTopic,
  PreviewCalendarSyncSnapshot,
  PreviewLeaderboardEntry,
  PreviewMasteryAnalyticsSnapshot,
  PreviewMasteryPoint,
  PreviewMissionScoreCard,
  PreviewMetricSummary,
  PreviewNotificationPayload,
  PreviewPushNotificationExample,
  PreviewPushSubscriptionStatus,
  PreviewPredictiveIntelligenceMetric,
  PreviewReadinessDashboardSnapshot,
  PreviewReadinessEtaSnapshot,
  PreviewReferralStat,
  PreviewSearchResult,
  PreviewStudyScheduleDay,
  PreviewWeatherBriefingData,
} from "./previewServiceTypes";

export const previewMockData = {
  analyticsSummaries: [
    { label: "Weekly score", value: "82%", delta: "+6 pts", tone: "positive" },
    { label: "Accuracy streak", value: "11 days", delta: "steady", tone: "neutral" },
    { label: "Weakest area", value: "Meteorology", delta: "focus now", tone: "warning" },
  ] satisfies PreviewMetricSummary[],
  masteryChartSeries: [
    { subject: "Air Navigation", mastery: 84, trend: "+7%" },
    { subject: "Meteorology", mastery: 58, trend: "+12%" },
    { subject: "Air Regulations", mastery: 76, trend: "+4%" },
    { subject: "Technical General", mastery: 69, trend: "+9%" },
  ] satisfies PreviewMasteryPoint[],
  leaderboardRankings: [
    { rank: 1, name: "A. Sharma", score: "96%", streak: "18 wins" },
    { rank: 2, name: "M. Evans", score: "94%", streak: "14 wins" },
    { rank: 3, name: "R. Patel", score: "92%", streak: "11 wins" },
    { rank: 14, name: "Current trainee", score: "84%", streak: "6 wins", currentUser: true },
  ] satisfies PreviewLeaderboardEntry[],
  bookmarkedTopics: [
    { title: "VOR Intercepts", kind: "Question set", count: "12 saved" },
    { title: "A320 Hydraulic Priorities", kind: "Flashcard deck", count: "8 cards" },
    { title: "DGCA Metar Decode", kind: "Revision note", count: "3 notes" },
  ] satisfies PreviewBookmarkTopic[],
  searchResults: [
    { title: "Crosswind landing technique", route: "/modules", tag: "Module" },
    { title: "FAA cloud clearances", route: "/blog/faa-cloud-clearances", tag: "Blog" },
    { title: "A320 electrical buses", route: "/a320-systems", tag: "Systems" },
    { title: "Navigation mock exam", route: "/mock-exams", tag: "Mock" },
  ] satisfies PreviewSearchResult[],
  referralStatistics: [
    { label: "Invites sent", value: "24" },
    { label: "Activated pilots", value: "7" },
    { label: "Reward credit", value: "₹2,800" },
  ] satisfies PreviewReferralStat[],
  aiCoachingResponse: {
    coachName: "Heading Coach",
    headline: "Your navigation pace is improving",
    summary: "You are converting review sessions into stronger timed results, but meteorology recall still softens under pressure.",
    strengths: ["Navigation formulas are trending upward", "Recent mock accuracy is stable above target"],
    focusAreas: ["Meteorology interpretation under time pressure", "Air regulations edge-case recall"],
    nextActions: ["Run one 20-question METAR drill", "Review alternate minima notes", "Take a mixed-timed mini mock tonight"],
  } satisfies PreviewAICoachingResponse,
  aiExplanation: {
    questionStem: "When intercepting a VOR radial inbound, which indication confirms proper capture?",
    correctAnswer: "The CDI centers with a valid TO indication and stabilized heading correction.",
    explanation: "Inbound radial capture requires reading the reciprocal course correctly and confirming TO/FROM logic before chasing the needle.",
    whyOthersMissIt: [
      "Pilots often confuse radial with track to station.",
      "A centered CDI without valid TO/FROM logic can still reflect the wrong side of the station.",
    ],
  } satisfies PreviewAIExplanation,
  weatherBriefing: {
    station: "VIDP",
    flightCategory: "MVFR",
    issuedAt: "14:30 IST",
    wind: "240/18G26KT",
    visibility: "5000m",
    ceiling: "BKN020",
    hazards: ["gusty crosswind", "isolated rain nearby"],
    summary: "Conditions remain flyable with caution. Expect moderate gusts on final and brief visibility reductions in passing showers.",
  } satisfies PreviewWeatherBriefingData,
  studySchedule: [
    {
      dateLabel: "Today",
      completion: "2 of 4 blocks complete",
      items: [
        { id: "sched-1", title: "Meteorology warm-up", block: "06:30 - 07:10", durationMinutes: 40, mode: "review", focus: "fronts and icing" },
        { id: "sched-2", title: "Navigation timed quiz", block: "19:00 - 19:35", durationMinutes: 35, mode: "quiz", focus: "wind triangle" },
      ],
    },
    {
      dateLabel: "Tomorrow",
      completion: "Planned",
      items: [
        { id: "sched-3", title: "DGCA mixed mock", block: "07:00 - 08:15", durationMinutes: 75, mode: "mock", focus: "multi-subject pressure set" },
        { id: "sched-4", title: "Air regs margin notes", block: "20:15 - 20:45", durationMinutes: 30, mode: "reading", focus: "CAR references" },
      ],
    },
  ] satisfies PreviewStudyScheduleDay[],
  predictiveMetrics: [
    {
      label: "Pass probability",
      value: "78%",
      confidence: "high confidence",
      trend: "up",
      narrative: "Recent timed performance and revision consistency support a likely pass if pace holds.",
    },
    {
      label: "Risk subject",
      value: "Meteorology",
      confidence: "medium confidence",
      trend: "flat",
      narrative: "Accuracy is recovering, but answer speed still drops on coded weather questions.",
    },
    {
      label: "Readiness ETA",
      value: "12 days",
      confidence: "medium confidence",
      trend: "down",
      narrative: "Current momentum shortens the estimated time to target readiness.",
    },
  ] satisfies PreviewPredictiveIntelligenceMetric[],
  readinessDashboard: {
    readinessPercentage: "78%",
    readinessTrend: "+5 pts this week",
    recommendationSummary: "Stay on the current cadence, but add one extra meteorology drill before the next mixed mock.",
    subjectBreakdown: [
      { subject: "Air Navigation", readiness: 84, trend: "+7%" },
      { subject: "Meteorology", readiness: 61, trend: "+9%" },
      { subject: "Air Regulations", readiness: 79, trend: "+3%" },
      { subject: "Technical General", readiness: 72, trend: "+4%" },
    ],
  } satisfies PreviewReadinessDashboardSnapshot,
  readinessEta: {
    estimatedReadyDate: "June 27, 2026",
    completionTrajectory: "On pace to cross target readiness in 12 days if current study cadence holds.",
    milestones: [
      { label: "65% readiness reached", targetDate: "Completed on Jun 12", status: "completed" },
      { label: "Mixed mock benchmark", targetDate: "Due Jun 19", status: "active" },
      { label: "80% readiness target", targetDate: "Due Jun 27", status: "upcoming" },
    ],
  } satisfies PreviewReadinessEtaSnapshot,
  masteryAnalytics: {
    distribution: [
      { label: "Strong subjects", value: "2" },
      { label: "Recovering subjects", value: "2" },
      { label: "Critical weak zones", value: "1" },
    ],
    strengths: ["Navigation calculations stay stable under timed conditions", "Air regulations recall is improving week over week"],
    weaknesses: ["Meteorology code interpretation still slows decision speed", "A320 electrical edge cases need one more review cycle"],
    suggestions: [
      "Pair timed METAR drills with answer review.",
      "Run one systems flashcard block after each mock.",
      "Revisit the lowest-scoring subject within 24 hours.",
    ],
  } satisfies PreviewMasteryAnalyticsSnapshot,
  missionScores: [
    {
      title: "Morning Navigation Sprint",
      score: "88 / 100",
      progressLabel: "9 of 10 checkpoints cleared",
      rankLabel: "Top 12% this week",
    },
    {
      title: "Meteorology Recovery Block",
      score: "74 / 100",
      progressLabel: "6 of 8 checkpoints cleared",
      rankLabel: "Needs reinforcement",
    },
    {
      title: "DGCA Mixed Mock",
      score: "81 / 100",
      progressLabel: "On track for next milestone",
      rankLabel: "Ranked 4 of 18",
    },
  ] satisfies PreviewMissionScoreCard[],
  notifications: [
    {
      id: "notif-1",
      title: "Keep your streak alive",
      body: "You have one unfinished study block remaining today.",
      category: "streak",
      timestampLabel: "2m ago",
      unread: true,
    },
    {
      id: "notif-2",
      title: "Referral reward unlocked",
      body: "A teammate activated your code and added new reward credit.",
      category: "referral",
      timestampLabel: "18m ago",
      unread: true,
    },
    {
      id: "notif-3",
      title: "Tomorrow's mock is ready",
      body: "Your scheduler staged a mixed-subject mock for the morning block.",
      category: "schedule",
      timestampLabel: "1h ago",
      unread: false,
    },
  ] satisfies PreviewNotificationPayload[],
  pushSubscriptionStatus: {
    channelLabel: "Heading Push Channel",
    browserLabel: "Chrome 126",
    deviceLabel: "Pixel 8 Pro",
    state: "subscribed",
    lastSynced: "Synced 5 minutes ago",
  } satisfies PreviewPushSubscriptionStatus,
  pushExamples: [
    {
      id: "push-1",
      title: "Study block starting soon",
      body: "Navigation timed quiz begins in 15 minutes.",
      device: "Mobile lock screen",
      deliveryLabel: "Queued for delivery",
    },
    {
      id: "push-2",
      title: "Streak at risk",
      body: "Complete one more session today to keep your 11-day streak.",
      device: "Desktop browser",
      deliveryLabel: "Recent example",
    },
  ] satisfies PreviewPushNotificationExample[],
  calendarSyncSnapshot: {
    accountLabel: "captain.trainee@heading.app",
    statusLabel: "Calendar sync healthy",
    upcoming: [
      {
        id: "cal-1",
        title: "Meteorology warm-up",
        dateLabel: "Tue, Jun 16",
        timeLabel: "06:30 - 07:10",
        calendarLabel: "Primary Study Calendar",
        exportType: "google",
      },
      {
        id: "cal-2",
        title: "DGCA mixed mock",
        dateLabel: "Wed, Jun 17",
        timeLabel: "07:00 - 08:15",
        calendarLabel: "ICS export feed",
        exportType: "ics",
      },
    ],
  } satisfies PreviewCalendarSyncSnapshot,
} as const;
