import type { FlagKeys } from "../../hooks/useFeatureFlags";

export type FeaturePreviewType = "component" | "route" | "api-only" | "none";

export type FeatureCategory =
  | "AI Features (cost-bearing)"
  | "Learning Features"
  | "UI/UX & System"
  | "Monetization & Growth"
  | "Announcement Banner"
  | "Study Scheduler"
  | "Analytics Intelligence"
  | "Mobile & Offline"
  | "Internal Rollout";

export type FeatureSideEffect =
  | "ai"
  | "auth"
  | "billing"
  | "calendar"
  | "notifications"
  | "offline-cache"
  | "payments"
  | "pwa"
  | "supabase-read"
  | "supabase-write"
  | "third-party-script"
  | "weather";

export interface FeatureDefinition {
  key: FlagKeys;
  title: string;
  description: string;
  category: FeatureCategory;
  adminVisible: boolean;
  previewType: FeaturePreviewType;
  routes: string[];
  sideEffects: FeatureSideEffect[];
  requiresAuth: boolean;
  requiresAdmin: boolean;
}

export const featureRegistry = {
  aiExplain: {
    key: "aiExplain",
    title: "AI Explain (Quiz)",
    description: "Explains answers dynamically within mock exams.",
    category: "AI Features (cost-bearing)",
    adminVisible: true,
    previewType: "component",
    routes: ["/quiz/:topicId"],
    sideEffects: ["ai", "auth"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  aiCoach: {
    key: "aiCoach",
    title: "AI Weak-Area Coach",
    description: "Generates performance study plans in Dashboard.",
    category: "AI Features (cost-bearing)",
    adminVisible: true,
    previewType: "component",
    routes: ["/quiz/:topicId"],
    sideEffects: ["ai", "auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  aiDiagnosis: {
    key: "aiDiagnosis",
    title: "AI Analytics Diagnosis",
    description: "Synthesizes diagnostic text from user history in Analytics.",
    category: "AI Features (cost-bearing)",
    adminVisible: true,
    previewType: "route",
    routes: ["/analytics", "/api/instructor/diagnosis"],
    sideEffects: ["ai", "auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  aiPractice: {
    key: "aiPractice",
    title: "Topic Practice Generator",
    description: "Creates practice questions per ATA chapter using AI.",
    category: "AI Features (cost-bearing)",
    adminVisible: true,
    previewType: "route",
    routes: ["/topic/:id", "/quiz/ai-generated-:id", "/api/instructor/practice"],
    sideEffects: ["ai", "auth"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  weatherBriefing: {
    key: "weatherBriefing",
    title: "Smart Weather Briefing",
    description: "Parses METAR lines into a readable AI summary.",
    category: "AI Features (cost-bearing)",
    adminVisible: true,
    previewType: "component",
    routes: ["/today", "/api/weather"],
    sideEffects: ["ai", "auth", "weather"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  mockExams: {
    key: "mockExams",
    title: "Mock Exams",
    description: "Toggle the main exams catalog.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/mock-exams", "/quiz/:topicId"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  topicPractice: {
    key: "topicPractice",
    title: "Topic Practice",
    description: "Free practice and module navigation.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/modules", "/topic/:id", "/quiz/:topicId"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  qotd: {
    key: "qotd",
    title: "Question of the Day",
    description: "Daily question challenge section.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/qotd"],
    sideEffects: ["supabase-read"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  spacedRepetition: {
    key: "spacedRepetition",
    title: "Spaced Repetition",
    description: "Smart review and weak-area algorithm.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "component",
    routes: ["/today", "/quiz/review"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  flashcards: {
    key: "flashcards",
    title: "Flashcard Layout",
    description: "Exam alternate view.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/quiz/:topicId", "/bookmarks"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  cockpitLayouts: {
    key: "cockpitLayouts",
    title: "Cockpit/Instrument Layouts",
    description: "Exam alternate view.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/quiz/:topicId"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  analytics: {
    key: "analytics",
    title: "Analytics Dashboard",
    description: "Show users their performance stats.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "route",
    routes: ["/analytics"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  masteryCharts: {
    key: "masteryCharts",
    title: "Mastery Charts",
    description: "Show subject and progress details in Stats view.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "component",
    routes: ["/analytics", "/today"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  blog: {
    key: "blog",
    title: "Blog / Content",
    description: "Enable the CMS articles.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "route",
    routes: ["/blog", "/blog/:slug", "/admin/blog"],
    sideEffects: ["supabase-read"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  examSeoPages: {
    key: "examSeoPages",
    title: "Exam SEO Pages",
    description: "Show the public mock exam promotional pages.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "route",
    routes: ["/exams/:examId"],
    sideEffects: [],
    requiresAuth: false,
    requiresAdmin: false,
  },
  a320Systems: {
    key: "a320Systems",
    title: "A320 Systems",
    description: "Technical system diagram study (Interactive).",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/topic/a320-systems", "/a320-systems", "/quiz/ai-generated-a320-systems"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  adsense: {
    key: "adsense",
    title: "Ad placements",
    description: "Toggle standard ad slots in the UI.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "component",
    routes: ["/", "/blog", "/exams/:examId"],
    sideEffects: ["third-party-script"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  pricingCheckout: {
    key: "pricingCheckout",
    title: "Pricing/Checkout",
    description: "Allows people to buy lifetime or subscribing.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "route",
    routes: ["/pricing", "/api/payment/create-order", "/api/payment/verify"],
    sideEffects: ["billing", "payments", "auth", "supabase-write"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  freeTrial: {
    key: "freeTrial",
    title: "Free Trial",
    description: "Enable the 3-day free trial system.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "component",
    routes: ["/pricing", "/api/start-trial"],
    sideEffects: ["auth", "billing", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  proGating: {
    key: "proGating",
    title: "Pro Gating",
    description: "If disabled, ALL users get premium features (skips auth check).",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "component",
    routes: ["/analytics", "/mock-exams", "/quiz/:topicId"],
    sideEffects: ["auth", "billing"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  maintenanceMode: {
    key: "maintenanceMode",
    title: "Maintenance Mode",
    description: "Locks out non-admins from using the app entirely.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: ["auth"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  cookieConsent: {
    key: "cookieConsent",
    title: "Cookie Consent Banner",
    description: "Show the EU GDPR cookie acceptance.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: ["third-party-script"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  announcementBanner: {
    key: "announcementBanner",
    title: "Show Top Banner",
    description: "Display an announcement block across all pages.",
    category: "Announcement Banner",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: [],
    requiresAuth: false,
    requiresAdmin: false,
  },
  announcementText: {
    key: "announcementText",
    title: "Announcement Text",
    description: "Copy displayed inside the site-wide announcement block.",
    category: "Announcement Banner",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: [],
    requiresAuth: false,
    requiresAdmin: false,
  },
  signupsOpen: {
    key: "signupsOpen",
    title: "Signups Open",
    description: "Toggle to restrict new sign ups (creates).",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/", "/login"],
    sideEffects: ["auth", "supabase-write"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  themeToggle: {
    key: "themeToggle",
    title: "Dark Mode Toggle",
    description: "Allow users to switch between light/dark themes.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: [],
    requiresAuth: false,
    requiresAdmin: false,
  },
  vivaPractice: {
    key: "vivaPractice",
    title: "VIVA Practice",
    description: "Oral exam simulation mode.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/quiz/viva"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  referralProgram: {
    key: "referralProgram",
    title: "Referral Program",
    description: "Show Refer & Earn section and track referral codes.",
    category: "Monetization & Growth",
    adminVisible: true,
    previewType: "route",
    routes: ["/referral"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  notifications: {
    key: "notifications",
    title: "Notifications",
    description: "Show the notification bell and real-time alerts.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/today"],
    sideEffects: ["notifications"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  bookmarksEnabled: {
    key: "bookmarksEnabled",
    title: "Bookmarks & Flashcards",
    description: "Allow users to bookmark questions and use flashcard view.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/bookmarks", "/quiz/bookmarks-review"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  searchEnabled: {
    key: "searchEnabled",
    title: "Global Search",
    description: "Enable the search overlay across all app content.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: ["supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  leaderboard: {
    key: "leaderboard",
    title: "Leaderboard",
    description: "Show ranked performance leaderboard (beta).",
    category: "Learning Features",
    adminVisible: true,
    previewType: "component",
    routes: [],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  offlineMode: {
    key: "offlineMode",
    title: "Offline Mode (PWA)",
    description: "Allow the app to work without internet via service worker cache.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/offline.html"],
    sideEffects: ["offline-cache", "pwa"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  pwaInstallPrompt: {
    key: "pwaInstallPrompt",
    title: "PWA Install Prompt",
    description: "Show the install-to-homescreen banner.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "component",
    routes: ["/*"],
    sideEffects: ["pwa"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  aiStudyScheduler: {
    key: "aiStudyScheduler",
    title: "AI Study Scheduler",
    description: "Generate and show adaptive study plans, missions, and schedule views.",
    category: "Study Scheduler",
    adminVisible: false,
    previewType: "route",
    routes: ["/today", "/study-plan", "/schedule", "/api/study/materialize", "/api/study/metrics"],
    sideEffects: ["ai", "auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  masterySnapshots: {
    key: "masterySnapshots",
    title: "Mastery Snapshots",
    description: "Capture subject mastery snapshots after quiz completion.",
    category: "Analytics Intelligence",
    adminVisible: false,
    previewType: "api-only",
    routes: ["/quiz/:topicId"],
    sideEffects: ["auth", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  examReadinessDashboard: {
    key: "examReadinessDashboard",
    title: "Exam Readiness Dashboard",
    description: "Show readiness gauge and subject ranking on the Today page.",
    category: "Analytics Intelligence",
    adminVisible: false,
    previewType: "component",
    routes: ["/today"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  sm2Algorithm: {
    key: "sm2Algorithm",
    title: "SM-2 Algorithm",
    description: "Use full SM-2 spaced repetition scheduling after answers.",
    category: "Internal Rollout",
    adminVisible: false,
    previewType: "api-only",
    routes: ["/quiz/:topicId"],
    sideEffects: ["auth", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  adaptiveRegen: {
    key: "adaptiveRegen",
    title: "Adaptive Regeneration",
    description: "Detect plan drift and regenerate study missions when needed.",
    category: "Study Scheduler",
    adminVisible: false,
    previewType: "component",
    routes: ["/today", "/api/study/adaptive-regen", "/api/study/mastery-check"],
    sideEffects: ["ai", "auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  masteryAnalytics: {
    key: "masteryAnalytics",
    title: "Mastery Analytics",
    description: "Show mastery heatmap and trend analytics for pro users.",
    category: "Analytics Intelligence",
    adminVisible: false,
    previewType: "component",
    routes: ["/today"],
    sideEffects: ["auth", "billing", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  missionScores: {
    key: "missionScores",
    title: "Mission Scores",
    description: "Show score chips on completed study missions.",
    category: "Study Scheduler",
    adminVisible: false,
    previewType: "component",
    routes: ["/today", "/schedule"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  sm2QualityTiming: {
    key: "sm2QualityTiming",
    title: "SM-2 Quality Timing",
    description: "Use response time to derive spaced-repetition answer quality.",
    category: "Internal Rollout",
    adminVisible: false,
    previewType: "api-only",
    routes: ["/quiz/:topicId"],
    sideEffects: ["auth", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  coachContextEnrichment: {
    key: "coachContextEnrichment",
    title: "Coach Context Enrichment",
    description: "Send mission rate and streak context to the coach engine.",
    category: "AI Features (cost-bearing)",
    adminVisible: false,
    previewType: "api-only",
    routes: ["/api/instructor/coach", "/api/study/adaptive-regen"],
    sideEffects: ["ai", "auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  examReadinessEta: {
    key: "examReadinessEta",
    title: "Exam Readiness ETA",
    description: "Show velocity and ETA projections in readiness views.",
    category: "Analytics Intelligence",
    adminVisible: false,
    previewType: "component",
    routes: ["/today"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  predictiveIntelligence: {
    key: "predictiveIntelligence",
    title: "Predictive Intelligence",
    description: "Show pass probability, subject risk, and success forecast analytics.",
    category: "Analytics Intelligence",
    adminVisible: false,
    previewType: "component",
    routes: ["/today", "/admin"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  advancedTesting: {
    key: "advancedTesting",
    title: "Advanced Testing",
    description: "Show adaptive mocks, DGCA simulator, and mistake analysis tools.",
    category: "Learning Features",
    adminVisible: false,
    previewType: "route",
    routes: ["/exam-centre"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  pwaEnhanced: {
    key: "pwaEnhanced",
    title: "Enhanced PWA",
    description: "Enable enhanced install experience and app shortcuts.",
    category: "Mobile & Offline",
    adminVisible: false,
    previewType: "component",
    routes: ["/*"],
    sideEffects: ["pwa"],
    requiresAuth: false,
    requiresAdmin: false,
  },
  offlineMissions: {
    key: "offlineMissions",
    title: "Offline Missions",
    description: "Cache study missions locally for offline access.",
    category: "Mobile & Offline",
    adminVisible: false,
    previewType: "api-only",
    routes: ["/today", "/schedule"],
    sideEffects: ["auth", "offline-cache", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  pushNotifications: {
    key: "pushNotifications",
    title: "Push Notifications",
    description: "Enable VAPID push subscription and reminder delivery.",
    category: "Mobile & Offline",
    adminVisible: false,
    previewType: "component",
    routes: ["/today", "/api/push/subscribe"],
    sideEffects: ["auth", "notifications", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  calendarSync: {
    key: "calendarSync",
    title: "Calendar Sync",
    description: "Enable ICS export and calendar sync actions.",
    category: "Mobile & Offline",
    adminVisible: false,
    previewType: "component",
    routes: ["/schedule"],
    sideEffects: ["auth", "calendar"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  missionEngine: {
    key: "missionEngine",
    title: "Mission Activation Engine",
    description: "Phase 6: deterministic single-mission loop (generate → start → complete → readiness → next) shown atop Today.",
    category: "Study Scheduler",
    adminVisible: true,
    previewType: "route",
    routes: ["/today", "/mission/complete", "/missions/history"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  xpSystem: {
    key: "xpSystem",
    title: "XP System",
    description: "Phase 7.1: append-only XP ledger. Gates XP event writes + reads. History only accrues while ON.",
    category: "Study Scheduler",
    adminVisible: true,
    previewType: "component",
    routes: ["/today", "/quiz", "/mission/complete"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  contentRegistry: {
    key: "contentRegistry",
    title: "Content Registry (Phase 1)",
    description: "Canonical content registry + hidden admin CRUD pages (Programs/Certifications/Aircraft/Topics). Resolver runs underneath regardless; this flag only exposes the admin registry pages.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "route",
    routes: ["/admin/registry"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: true,
  },
  learningContext: {
    key: "learningContext",
    title: "Learning Context (Phase 2)",
    description: "Learning profiles + enrollments model. Gates onboarding dual-write, the hidden Learning Context settings page, and admin enrollment ops. Resolver falls back to target_exam regardless. OFF = production behaviour unchanged.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "route",
    routes: ["/learning-context", "/admin/registry/enrollments"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: false,
  },
  contentCms: {
    key: "contentCms",
    title: "Content CMS (Phase 3)",
    description: "Admin content management system: hierarchy tree, draft question editor, validation, search, versioning, bulk ops. Admin-only, no nav link, no student-facing effect. OFF = hidden.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "route",
    routes: ["/admin/cms"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: true,
  },
  contentImport: {
    key: "contentImport",
    title: "Content Import Engine (Phase 4)",
    description: "Staged bulk import pipeline: CSV/JSON → staging tables → normalize/validate/dedupe → preview → commit as draft questions. Admin-only. OFF = hidden. No production content is touched until admin confirms.",
    category: "UI/UX & System",
    adminVisible: true,
    previewType: "route",
    routes: ["/admin/content-import"],
    sideEffects: ["auth", "supabase-read", "supabase-write"],
    requiresAuth: true,
    requiresAdmin: true,
  },
  contentDeliveryEngine: {
    key: "contentDeliveryEngine",
    title: "Content Delivery Engine (Phase 5)",
    description: "Unified content scope resolver — resolveContentScope() wired into Modules, Missions, Quiz, Analytics, Scheduler, and AI. All consumers derive subject/module/topic eligibility from one canonical resolver. OFF = legacy per-component filtering. ON = single engine drives everything.",
    category: "Internal Rollout",
    adminVisible: true,
    previewType: "none",
    routes: ["/modules", "/quiz/:topicId", "/today", "/analytics", "/admin/registry"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: true,
  },
  learningHierarchy: {
    key: "learningHierarchy",
    title: "Learning Hierarchy (Phase 8)",
    description: "Student learning platform: Cert→Subject→Module→Topic hierarchy in Modules view, per-module progress tracking, topic progress cards, hierarchy dashboard tiles, and /course overview page. Requires contentDeliveryEngine ON for full scope filtering. OFF = existing flat module grid unchanged.",
    category: "Learning Features",
    adminVisible: true,
    previewType: "route",
    routes: ["/modules", "/topic/:id", "/today", "/course"],
    sideEffects: ["auth", "supabase-read"],
    requiresAuth: true,
    requiresAdmin: false,
  },
} satisfies { [K in FlagKeys]: FeatureDefinition & { key: K } };

export const featureControlSections: FeatureCategory[] = [
  "AI Features (cost-bearing)",
  "Learning Features",
  "Study Scheduler",
  "UI/UX & System",
  "Monetization & Growth",
  "Internal Rollout",
];

export const adminFeatureDefinitions = featureControlSections.map((category) => ({
  category,
  features: Object.values(featureRegistry).filter(
    (feature) => feature.adminVisible && feature.category === category
  ),
}));

export const announcementBannerFeature = featureRegistry.announcementBanner;
export const announcementTextFeature = featureRegistry.announcementText;
